### ISSUE TITLE
GPS positioning in apps not working (Titan Slim)

### ISSUE THREAD

**Issue by michalko58** [rumplestilzken/unihertz_titan_lineageos20#13]
GPS positioning in apps not working

The GPS test application finds satellites (for example, it sees 34 and uses 9 of them), but other applications are unable to determine their location.

Test application:

- GPS Test

Affected apps:

- Google maps
- Mapy.cz
- Gismeteo
- Telegram

Location permissions are granted
None of the apps complain about not having location access
Some applications (GPS Test, Google Maps, Telegram) display an icon about the use of location, others do not (Mapy.cz).

It seems that after some time (a few hours after trying to locate), some apps seem to detect the location from the time they were tested, as if they have access to some location history, but it's turned off (Google location history).

**Comment by rumplestilzken** [comment]
Verified on Slim.

**Comment by michalko58** [comment]
Seems that GPS positioning started working by itself:-)
