### ISSUE TITLE
Take a photo by pressing the space bar on the hw keyboard

### ISSUE THREAD

**Issue by michalko58** [rumplestilzken/unihertz_titan_lineageos20#15]
Blackberry Android phones (Key One and Key2) had the ability to take a picture with a single press of the spacebar on the hw keyboard, which was cool. This was available on Blackberries with BB OS too.

On the Unihertz Titan and Titan Slim, it was only possible to take a photo by double-clicking, which often resulted in the phone moving and blurring the photo.

Therefore, it would be nice if there was an option to create a photo with one press of the space bar on the hw keyboard.

**Comment by rumplestilzken** [comment]
Will be included in the next release.
