### ISSUE TITLE
Double Press Home Button to actuate Home action

### ISSUE THREAD

**Issue by rumplestilzken** [rumplestilzken/unihertz_titan_lineageos20#3]
This would allow the user to be forgiven for touching the Home capacitive button on accident while typing. Instead making them Double Tap to actuate the Home action.

**Comment by rumplestilzken** [comment]
https://m.apkpure.com/key-mapper/io.github.sds100.keymapper

Use Key Mapper to map the home button to do nothing on single tap and go home on double tap.

**Comment by Ansbaradigeidfran** [comment]
Key Mapper is a partial workaround (after enabling the accesibility settings): it can stop a single press of the home button from actuating the Home action, but it doesn't stop the fingerprint sensor from generating a tactile vibration on a single press.

Key Mapper has the option to *enable* a custom vibration, but when turned off the system default one takes place instead.
