### ISSUE TITLE
Google Apps on Titan Slim?

### ISSUE THREAD

**Issue by MrMEEE** [rumplestilzken/unihertz_titan_lineageos20#30]
Hi

How do I install Google Apps on the Titan Slim?

I can't seem to get the recovery to install them (adb sideload fails about halfway through and sdcard won't mount)

Regards

**Comment by rumplestilzken** [comment]
* Google Play Store can be installed with [wacko's Magisk module](https://github.com/wacko1805/MagiskGapps) on the bvn version if wanted. If you get a "Not Certified" warning [register with google](https://www.google.com/android/uncertified/) and within a few minutes your Google Play will work.
