### ISSUE TITLE
keycodes for fn and sym on the pocket and slim

### ISSUE THREAD

**Issue by runoono** [rumplestilzken/unihertz_titan_lineageos20#31]
I'm writing a keyboard tailored for the titan series, I wanna map the FN and SYM keys but I dont have a pocket or slim to find out what keycodes they output, would appreaciate an answer

**Comment by rumplestilzken** [comment]
SYM is MENU

**Comment by runoono** [comment]
okay, I'm using KeyEvent.KEYCODE_MENU which should be 82

**Comment by rumplestilzken** [comment]
function is PROG_RED, 183
