### ISSUE TITLE
No access to IR Blaster functionnality for Titan Pocket

### ISSUE THREAD

**Issue by ttttg2** [rumplestilzken/unihertz_titan_lineageos20#32]
Not sure if the hardware is open but would be fun to access the IR sensor.
IR Remote from F-Droid doesn't detect the IR blaster. 
Also would be fun to access IR Blaster functions through command line but no idea if this could be possible.

**Comment by rumplestilzken** [comment]
The hardware does not support IR Blaster.

Verified by using su; dmesg | grep -i cir
