### ISSUE TITLE
Alt buttons gives wrong characters 

### ISSUE THREAD

**Issue by MrMEEE** [rumplestilzken/unihertz_titan_lineageos20#33]
Hi

I'm on a Titan Slim, and for some reason I get the from special characters when holding down ALT.. 

I think it worked at some point, but I'm not sure.. 

I can change the layout under the system settings, but no matter what I try, it doesn't match the keyboard...

What to do?

Someway to reset the options of the PKB?

Thanks for all the work

**Comment by rumplestilzken** [comment]
Did you set the language to english instead of default?

**Comment by MrMEEE** [comment]
Language or keyboard layout?

System language is set to Danish, I have tried setting the keyboard layout to both "english (USA)", "English (Great Britain)", Danish and a lot others

**Comment by MrMEEE** [comment]
And also to "Standard"

**Comment by rumplestilzken** [comment]
Changing the default keymap causes issues. This is the same on stock. Try to reset it to default and see if the keymap fixes itself.

**Comment by MrMEEE** [comment]
Where do I change the default keymap?

Under
System -> Languages and input -> Physical keyboard
I have now disabled everything and it says "Default"..

Still doesn't work

**Comment by rumplestilzken** [comment]
Give a display keymap of the first alt row of keys.

**Comment by MrMEEE** [comment]
normal and capitalized letters are correct, but holding ALT I get the following
![Screenshot_20230913-182642_Messages](https://github.com/rumplestilzken/gargoyle_lineageos20/assets/768031/24124218-37f3-41d5-9f4e-95862043af8d)

A lot of the buttons gives nothing

**Comment by rumplestilzken** [comment]
Try reflashing with slim variant without setting keyboard settings and let me know where you stand.
