### ISSUE TITLE
Titan Slim - gargoyle 1.4 - Bluetooth setup broken

### ISSUE THREAD

**Issue by PlazmaSpirit** [rumplestilzken/unihertz_titan_lineageos20#49]
While going through the first boot setup, the step to setting up bluetooth correctly cannot be completed as the phh Treble settings do not have a toggle for "system wide BT HAL", only an option for setting the bluetooth workaround. Even after setting this to "mediatek" and rebooting, there is no BT HAL toggle anywhere in any of the phh Treble menus

Edit: I should also note I tried reinstalling the entire system again to start from scratch, this has not fixed the issue

**Comment by NotAlexNoyle** [comment]
Same issue here. I have captured the relevant logs:

https://pastebin.com/raw/MTxjegCf

https://pastebin.com/raw/2h0PbRaA

Even on 1.2 I was unable to pair my QC35s, but on 1.4 Bluetooth won't turn on at all.

**Comment by rumplestilzken** [comment]
This is not limited to Slim

**Comment by TiTi65** [comment]
Hi, same on Titan too, I've got the menus, but, not working...do you need some logcat to investigate ?

**Comment by TiTi65** [comment]
hello, did somebody found a workarround ?

**Comment by rumplestilzken** [comment]
This has been resolved, i am building new images now, they will be up in a few hours.

**Comment by TiTi65** [comment]
I'll keep you posted regarding this ;)

**Comment by TiTi65** [comment]
I'm going on this release this WE.
Any chance to upgrade without all re installing ?

**Comment by rumplestilzken** [comment]
You just need to flash new system/super. Dont need to touch userdata.

**Comment by TiTi65** [comment]
I will try and hope :),
thanks !

**Comment by TiTi65** [comment]
hello,
it worked fine.
no user data lost.
bluetooth is working much better than the original's unihertz ROM.
no more cut in sound playing.
is it thanks to workarround ou hardware BT or anything else ?

kind regards

**Comment by rumplestilzken** [comment]
The build was corrupted on the initial release.
