### ISSUE TITLE
Unlock operation is not allowed

### ISSUE THREAD

**Issue by AntiSol** [rumplestilzken/unihertz_titan_lineageos20#54]
Hello, thanks for all your hard work on this device! 

I'm trying to root (and maybe install lineageos) on my EU EEA titan. I'm following [these instructions](https://github.com/rumplestilzken/gargoyle_lineageos20/issues/45#issuecomment-1988643640) and [these ones](https://gist.github.com/rumplestilzken/1d66b6e3aae16ece75f06b00d466d246) but I can't seem to get the device unlocked for flashing. I run `fastboot flashing unlock` and press volume up on the device (immediately, within 1 second), and I get: 
```(bootloader) Start unlock flow

FAILED (remote: 
Unlock operation is not allowed
)
finished. total time: 3.475s
```

Any ideas?

**Comment by rumplestilzken** [comment]
You need to boot into the OS and enable OEM unlocking in developer
settings.

**Comment by AntiSol** [comment]
wow that's the fastest reply I've ever seen!

Looks like I've used the wrong boot.img or something, I've now got the "orange state" boot loop. Looks like I'll have to re-flash back to stock android and try again.

IIUC I need to flash the stock android 9 and then upgrade to android 10, correct? I can't flash directly to android 10?

Thanks

**Comment by rumplestilzken** [comment]
If you indeed have an eea unit, flash 9. Then sideload 10.  Use 10's
boot.img to create magisk boot image.

**Comment by AntiSol** [comment]
it is the eu eea version, unihertz told me that based on the device's version info. It came with android 10 on it.
hmm that is the boot.img that I used, the one from 2021020416_g61v71c2k_dfl_eea-ota.zip. 
I installed magisk 25 to get the vbmeta option per the other issue I linked to.
does that sound right? Any other tips / advice? :) 

I'm out of time tonight, I'll have to give it another shot tomorrow. Thanks for your help

**Comment by rumplestilzken** [comment]
If it came with android 10 it is likely a UFS model. Try using those roms to flash. Check my wiki http://rumplestilzken.com:14005/Unihertz/StockResources

If it is not ufs you will get a message about mismatch of memory type. No harm done.

**Comment by AntiSol** [comment]
I'm sorry, I haven't had time to come back to this properly and try out the lineageos build. I did manage to get root successfully though, so you can close this issue if you want. Thanks so much for your help, I have a feeling we'll talk again when I get to it ;)
